import Head from "next/head";
import { Inter } from "next/font/google";
import AptosWalletConnect from "@/components/Section/AptosWalletConnect";
import MediaContent from "@/components/Section/MediaContent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" flex flex-col justify-center items-center my-12">
          <AptosWalletConnect />
          <MediaContent/>
        </div>
      </main>
    </>
  );
}
