import Head from "next/head";
import AptosWalletConnect from "@/components/Section/AptosWalletConnect";
import MediaContent from "@/components/Section/MediaContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <AptosWalletConnect />
          <MediaContent />
        </div>
      </main>
    </>
  );
}
